var Labels = function () {
    return {
        es: {
            loading: "Cargando...",
            personnel_information_label: "Información del Cliente",
            business_information_label: "Información de la Empresa",
            client_state_confirm: "¿Está seguro de cambiar el estado del cliente?",
            client_cancel_confirm: "¿Está seguro que desea cancelar este cliente?",
            client_delete_confirm: "¿Está seguro que desea eliminar este cliente?",
            client_reset_passwd: "¿Está seguro que desea resetear la contraseña para el administrador del cliente?",
            personnel_data: "Datos Personales",
            business_data: "Representante Legal",
            identity_number_length: "La Cédula debe contener 10 dígitos",
            ruc_number_length: "El RUC debe contener 13 dígitos",
            identity_wrong: "La Cédula es incorrecta",
            ruc_wrong: "El RUC es incorrecta",
            options: 'Opciones',
            edit: 'Editar',
            inDebt: 'En Mora',
            devices: 'Dispositivos',
            add: 'Agregar dispositivo',
            Delete: 'Eliminar',
            activate: 'Activar',
            cancel: 'Cancelar',
            suspend: 'Suspender',
            atDay: 'Al Día',
            password_validate: 'Ingrese la contraseña',
            password_confirmation: 'Esta seguro que desea cambiar la contraseña?',
            change_success: 'Cambio realizado con éxito',
            change_fail: 'Se produjo un error al intentar cambiar la contraseña',
            client_change_passwd: 'Las contraseñas no coinciden.',
            password_minimun: 'Contraseña requiere al menos 6 caracteres',
            user_change_passwd: 'Las contraseñas no coinciden.',
            name_user_exist: 'Nombre de usuario existente',
            user_delete_confirm: '¿Está seguro que desea eliminar este usuario?',
            options: 'Opciones',
            edit_user: 'Editar Usuario',
            delete_user: 'Eliminar Usuario',
            profile_delete_confirm: '¿Está seguro que desea eliminar este perfil?',
            edit_profile: 'Editar Perfil',
            delete_profile: 'Eliminar Perfil',
            field_empty: 'Debe ingresar su nombre de usuario',
            no_user: 'No existe un usuario con ese nombre',
            no_email: 'No existe una dirección de correo electrónico asignado a su cuenta. Por favor comuníquese con su administrador del sistema para obtener el soporte necesario',
            email_invalid: 'Dirección de correo electrónico invalida, no pertenece al usuario',
            cancel_order_confirm: '¿Está seguro de cancelar la orden seleccionada?',
            edit_order_confirm: '¿Está seguro que desea guardar los cambios?',
            ph_search: 'Buscar...',
            clients: 'Clientes',
            type_here: 'Escriba aquí...',
            device_wait: 'Espere hasta que el formulario haya sido cargado completamente',
            dev_assign_incomplete: 'Existen datos que no han sido especificados correctamente',
            has_roaming: 'Tiene roaming',
            more_information: 'Más Información',
            execute: 'Ejecutar',
            loading: "Cargando...",
            sending_command: "Enviando comando",
            command_success: "Comando enviado",
            command_timeout: "Tiempo de espera superado",
            at_missing: "Todo comando debe empezar con el prefijo AT",
            deactivate_confirmation: "Esta seguro que desea dar de baja este equipo ?",
            deactivate_success: "El dispositivo fue desactivado con exito",
            deactivate_fail: "Se produjo un error al intentar dar de baja el dispositivo",
            type_here_imei: 'Ingrese el IMEI',
            type_here_feature: 'Ingrese la característica',
            type_here_report: 'Ingrese el reporte',
            type_here_alert: 'Ingrese la alerta',
            type_here_device_type: 'Ingrese el tipe de dispositivo',
            type_here_device_model: 'Ingrese el modelo de dispositivo',
            deactivate: 'Desactivar',
            support: 'Soporte',
            send_command: 'Enviar comando',
            change_device: 'Cambio de dispositivo',
            change_simcard: 'Cambio Simcard',
            imei_current: 'Imei actual',
            imei_new: 'Imei nuevo',
            change_fail: "Se produjo un error al intentar registrar los cambios",
            change_confirmation: "Esta seguro que desea realizar el cambio en este equipo ?",
            change_validate: "Ingrese el IMEI",
            imei: "IMEI",
            icc: "ICC",
            alias: "Alias",
            phone: "Teléfono",
            gps_status: "Estado GPS",
            last_transmission_date: "Última transmisión",
            last_lat_lng: "Última (lat, lng)",
            activation_status: "Estado activación",
            activation_date: "Fecha de activación",
            categoria: "Categoría",
            installation_date: "Fecha de Instalación",
            installed_by: "Instalado por",
            generating: "Generando...",
            phone_in_use: "El teléfono especificado se encuentra en uso",
            phone_number_wrong: "MSISDN incorrecto",
            phone_number_length: "MSISDN debe contener hasta 20 dígitos",
            firmware: "V. Firmware",
            url_required: "El valor de la URL es obligatorio",
            feature_required: "Debe seleccionar una característica",
            report_required: "Debe seleccionar un reporte",
            portal_required: "Debe seleccionar un portal",
            required_field: "Campo requerido",
            url_unavailable: "La URL ingresada no se encuentra disponible",
            delete_url_confirmation: "Está seguro que desea eliminar esta URL?",
            delete_feature_confirmation: "Está seguro que desea eliminar esta característica?",
            delete_confirmation: "Está seguro que desea eliminar este elemento?",
            delete_business_confirmation: "Está seguro que desea eliminar este canal?",
            url_delete_error: "Ha existido un problema y la URL no ha sido eliminada",
            feature_delete_error: "Ha existido un problema y la característica no ha sido eliminada",
            delete_error: "Ha existido un problema y el elemento no ha sido eliminado",
            delete_error_have_url: "Este canal tiene asignadas URLs por lo tanto no puede ser eliminado, borre las URLs para poder proceder",
            alert_required: "Debe seleccionar una alerta",
            shipments: "Embarques",
            editZone: "Editar Zona",
            edit_zone: "Editar Zona",
            edit_driver: "Editar Conductor",
            assing_zone: "Asignar Zona",
            delete_zone: "Eliminar Zona",
            delete_delivery: "Eliminar Entrega",
            edit_delivery: "Editar Entrega",
            delivery_delete_confirm: "¿Está seguro que desea eliminar esta entrega?",
            zone_delete_confirm: "¿Está seguro que desea eliminar esta zona?"

        },
    };
}